/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FlightSearchBound
    /// </summary>
    [DataContract]
    public partial class FlightSearchBound :  IEquatable<FlightSearchBound>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightSearchBound" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FlightSearchBound() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightSearchBound" /> class.
        /// </summary>
        /// <param name="Flights">Flights (required).</param>
        /// <param name="Duration">The duration of this bound, including layover time, expressed in the format hh:mm.</param>
        public FlightSearchBound(List<FlightSearchSegment> Flights = default(List<FlightSearchSegment>), string Duration = default(string))
        {
            // to ensure "Flights" is required (not null)
            if (Flights == null)
            {
                throw new InvalidDataException("Flights is a required property for FlightSearchBound and cannot be null");
            }
            else
            {
                this.Flights = Flights;
            }
            this.Duration = Duration;
        }
        
        /// <summary>
        /// Gets or Sets Flights
        /// </summary>
        [DataMember(Name="flights", EmitDefaultValue=false)]
        public List<FlightSearchSegment> Flights { get; set; }

        /// <summary>
        /// The duration of this bound, including layover time, expressed in the format hh:mm
        /// </summary>
        /// <value>The duration of this bound, including layover time, expressed in the format hh:mm</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public string Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlightSearchBound {\n");
            sb.Append("  Flights: ").Append(Flights).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FlightSearchBound);
        }

        /// <summary>
        /// Returns true if FlightSearchBound instances are equal
        /// </summary>
        /// <param name="other">Instance of FlightSearchBound to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlightSearchBound other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Flights == other.Flights ||
                    this.Flights != null &&
                    this.Flights.SequenceEqual(other.Flights)
                ) && 
                (
                    this.Duration == other.Duration ||
                    this.Duration != null &&
                    this.Duration.Equals(other.Duration)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Flights != null)
                    hash = hash * 59 + this.Flights.GetHashCode();
                if (this.Duration != null)
                    hash = hash * 59 + this.Duration.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
