/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LocationResponse
    /// </summary>
    [DataContract]
    public partial class LocationResponse :  IEquatable<LocationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationResponse" /> class.
        /// </summary>
        /// <param name="City">Information for any &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city which corresponds to the provided code.</param>
        /// <param name="Airports">Information for any IATA airport located in the provided &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city or which corresponds to the provided code.</param>
        public LocationResponse(CityInformation City = default(CityInformation), List<AirportInformation> Airports = default(List<AirportInformation>))
        {
            this.City = City;
            this.Airports = Airports;
        }
        
        /// <summary>
        /// Information for any &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city which corresponds to the provided code
        /// </summary>
        /// <value>Information for any &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city which corresponds to the provided code</value>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public CityInformation City { get; set; }

        /// <summary>
        /// Information for any IATA airport located in the provided &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city or which corresponds to the provided code
        /// </summary>
        /// <value>Information for any IATA airport located in the provided &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; of the city or which corresponds to the provided code</value>
        [DataMember(Name="airports", EmitDefaultValue=false)]
        public List<AirportInformation> Airports { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LocationResponse {\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Airports: ").Append(Airports).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LocationResponse);
        }

        /// <summary>
        /// Returns true if LocationResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of LocationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LocationResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.City == other.City ||
                    this.City != null &&
                    this.City.Equals(other.City)
                ) && 
                (
                    this.Airports == other.Airports ||
                    this.Airports != null &&
                    this.Airports.SequenceEqual(other.Airports)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.City != null)
                    hash = hash * 59 + this.City.GetHashCode();
                if (this.Airports != null)
                    hash = hash * 59 + this.Airports.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
